# Generated by Django 4.1.3 on 2023-01-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={"verbose_name_plural": "Posts"},
        ),
    ]
